import os

TWITTER_CONSUMER_KEY = os.environ["TWITTER_CONSUMER_KEY"]
TWITTER_CONSUMER_SECRET = os.environ["TWITTER_CONSUMER_SECRET"]
TWITTER_ACCESS_TOKEN_KEY = os.environ["TWITTER_ACCESS_TOKEN_KEY"]
TWITTER_ACCESS_TOKEN_SECRET = os.environ["TWITTER_ACCESS_TOKEN_SECRET"]

MY_GITHUB_ACCESS_KEY = os.environ["MY_GITHUB_ACCESS_KEY"]
GITHUB_REPO_URL = "juhyunc/chikax2-bot"
GITHUB_ISSUE_ID = 1
TWEET_LENGTH_LIMIT = 140
 
